; PlatformIO Project Configuration File
;
; 在本文件里切换发射端 / 接收端：
; 1. 发射端：启用 ROLE_TX，注释掉 ROLE_RX
; 2. 接收端：启用 ROLE_RX，注释掉 ROLE_TX
; 3. upload_port / monitor_port 按当前插上的板子 COM 口填写

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

monitor_speed = 115200

; 按当前连接的板子修改串口号
; upload_port = COM6
; monitor_port = COM6

lib_deps =
  jgromes/RadioLib @ ^7.3.0

; 角色切换：二选一
;build_flags = -D ROLE_TX
build_flags = -D ROLE_RX
